baseURL = "https://blog.felixbreidenstein.de"
languageCode = "de-de"
title = "blog.felixbreidenstein.de"
theme = ["hugo-notice", "anatole"]
paginate = 10

[params]
title = "Felix Breidenstein"
author = "Felix Breidenstein"
profilePicture = "img/avatar.jpg"
description = """
My hands are typing words...
"""
doNotLoadAnimations = true # Animations are loaded by default

displayMode = "dark"
contentratio = 0.7
customCss = ["css/syntax.css"]

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://de.linkedin.com/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:mail@example.com"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
