baseURL = "https://blog.felixbreidenstein.de"
languageCode = "de-de"
title = "blog.felixbreidenstein.de"
theme = ["hugo-notice", "anatole"]

pygmentsCodeFences = true
pagination.pagerSize = 5

[permalinks]
  posts = "/:year/:title/"


[params]
    title = "My hands are typing words..."
    author = "Felix Breidenstein"
    description = "#FleazBloggt"
    profilePicture = "/img/avatar.jpg"
    doNotLoadAnimations = true
    contentratio = 0.7

    [[params.socialIcons]]
    icon = "fab fa-mastodon"
    title = "Mastodon"
    url = "https://chaos.social/@fleaz"

    [[params.socialIcons]]
    icon = "fab fa-github"
    title = "Github"
    url = "https://github.com/fleaz"

    [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "E-Mail"
    url = "mailto:blog@felixbreidenstein.de"
