baseURL = "https://blog.felixbreidenstein.de"
languageCode = "de-de"
title = "blog.felixbreidenstein.de"
theme = "hpstr-fork"

[permalinks]
  posts = "/:year/:title/"

pygmentsCodeFences = true
paginate = 5

[params]
	subtitle = "Wie Twitter nur mit mehr Buchstaben"
    show_summary = true
	comments = false
	share = false
	[params.author]
		name = "Felix Breidenstein (er/he)"
		avatar = "/img/avatar.jpg"
		bio = "3D Drucker, Fahrräder, Computer"
		github = "fleaz"
		twitter = "fleaz_"
		instagram = "f_breidenstein"
	[params.image]
		feature = "/img/header.jpg"
		credit = "myfree"
		creditlink = "http://www.dargadgetz.com/ios-7-abstract-wallpaper-pack-for-iphone-5-and-ipod-touch-retina/"
